viewer/src/main/webapp/viewer-html/ibis/IbisEdit.js
viewer/src/main/webapp/viewer-html/ibis/WorkflowStatus.js

EKU 17/11 Bewerken tool moet in de titel of boven de tabbladen de naam van het bedrijventerrein, de gemeente  en eventueel het RIN nummer tonen.

terrein naam, gemeente, RIN nummer op edit popup

---

pom.xml
src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/viewer-html/ibis/IbisEdit-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisLocationFinder-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisMerge-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisReport-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisSplit-config.js

API Aanpassingen voor Flamingo 4.7.0

---

src/site/markdown/notes.md
viewer-admin/src/main/webapp/META-INF/context.xml
viewer/pom.xml
viewer/src/main/java/nl/b3p/viewer/stripes/IbisReportsActionBean.java
viewer/src/main/webapp/META-INF/context.xml
viewer/src/main/webapp/viewer-html/ibis/IbisEdit.js
viewer/src/main/webapp/viewer-html/ibis/IbisLocationFinder-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisReports-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisReports.js
viewer/src/main/webapp/viewer-html/ibis/components.json

see: https://b3partners.github.io/flamingo-ibis/notes.html for configuration

Rapportage tool

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/java/nl/b3p/viewer/ibis/util/WorkflowUtil.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisEditFeatureActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisMergeFeaturesActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisSplitFeatureActionBean.java

Voorkom ontstaan van meer dan 1 archiefrecord van een object per mutatiedatum

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/java/nl/b3p/viewer/ibis/util/WorkflowUtil.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisEditFeatureActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisMergeFeaturesActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisSplitFeatureActionBean.java

Op verzoek van EKU.
revert 1b642c0b3f568b360b1f45fa676fab4120b2b547 (PR #60)

Revert IBPV-028 Voorkom ontstaan van meer dan 1 archief record per datum per object

---

.travis.yml
viewer/src/main/webapp/WEB-INF/xsl/print/ibisfactsheet.xsl

rechts uitlijnen van getallen en aanpassing kolombreedte voor "terreinkenmerken" tabel

---

viewer/src/main/webapp/WEB-INF/classes/log4j.properties
viewer/src/main/webapp/WEB-INF/xsl/print/A3_Landscape.xsl
viewer/src/main/webapp/WEB-INF/xsl/print/A3_Portrait.xsl
viewer/src/main/webapp/WEB-INF/xsl/print/A4_Landscape.xsl
viewer/src/main/webapp/WEB-INF/xsl/print/A4_Portrait.xsl
viewer/src/main/webapp/WEB-INF/xsl/print/calc481.xsl
viewer/src/main/webapp/WEB-INF/xsl/print/ibisfactsheet.xsl
viewer/src/main/webapp/WEB-INF/xsl/print/ibisstyles.xsl
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet.js

close #88 
close flamingo-geocms/flamingo#1289

Update factsheet en printstylesheets

---

pom.xml
src/site/markdown/development.md
viewer-admin/src/main/webapp/WEB-INF/web.xml
viewer/src/main/webapp/WEB-INF/web.xml

http://ibis.b3p.nl/solr/ -> https://bedrijventerreinen.gelderland.nl/solr/
close #95

update solr url 

---

viewer/src/main/webapp/viewer-html/ibis/WorkflowStatus.js

[LGTM] correct typo

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/java/nl/b3p/viewer/stripes/IbisReportsActionBean.java

Gebruik "wgr_naam" om regio filter in te stellen

---

src/site/apt/releasenotes.apt.vm
viewer-admin/src/main/webapp/META-INF/context.xml
viewer-admin/src/main/webapp/WEB-INF/classes/log4j.properties
viewer-admin/src/main/webapp/WEB-INF/web.xml
viewer/src/main/webapp/META-INF/context.xml

zie: https://github.com/flamingo-geocms/flamingo/pull/972

Fix solr indexing schedule

---

pom.xml
viewer-admin/src/main/webapp/about.jsp
viewer/src/main/java/nl/b3p/viewer/ibis/util/WorkflowUtil.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisEditFeatureActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisFeatureInfoActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisMergeFeaturesActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisReportsActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisSplitFeatureActionBean.java
viewer/src/main/webapp/about.jsp

Upgrade dependencies naar Flamingo 5.7.0-SNAPSHOT

---

viewer/src/main/webapp/viewer-html/ibis/IbisEdit.js

wordt en was boven de kolommen van ibisedit zetten

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/WEB-INF/xsl/print/ibisfactsheet.xsl
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet.js

min. en max. kavelprijs per m2 in factsheet

---

src/site/apt/releasenotes.apt.vm
viewer-admin/src/main/webapp/WEB-INF/web.xml
viewer/src/main/java/nl/b3p/viewer/ibis/util/DateUtils.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisEditFeatureActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisFeatureInfoActionBean.java
viewer/src/main/java/nl/b3p/viewer/stripes/IbisFeatureInfoUtilsActionBean.java
viewer/src/main/java/nl/b3p/viewer/util/IbisFeatureToJson.java
viewer/src/main/webapp/WEB-INF/classes/log4j.properties
viewer/src/main/webapp/WEB-INF/jsp/app_overrides.jsp
viewer/src/main/webapp/WEB-INF/web.xml
viewer/src/main/webapp/viewer-html/ibis/IbisEdit.js
viewer/src/main/webapp/viewer-html/ibis/IbisEditHistorisch-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisEditHistorisch.js
viewer/src/main/webapp/viewer-html/ibis/WorkflowStatus.js
viewer/src/main/webapp/viewer-html/ibis/components.json
viewer/src/test/java/nl/b3p/viewer/ibis/util/DateUtilsTest.java

component om historische kavels te bewerken

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/java/nl/b3p/viewer/stripes/IbisEditFeatureActionBean.java
viewer/src/main/webapp/viewer-html/ibis/IbisEdit-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisEdit.js
viewer/src/main/webapp/viewer-html/ibis/IbisEditHistorisch.js

zodat kavels met status bewerkt kunnen worden afgekeurd (==verwijderd)
close #144

Voeg een "afkeuren" knop toe op de IbisEdit component

---

src/main/ddl/upgrade3.1-4.0-attribuut-alias.sql
src/main/ddl/upgrade3.1-4.0-views.sql
src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet.js

close #138 
needs https://github.com/flamingo-geocms/flamingo/pull/1800

extra kolommen voor thema veroudering

---

pom.xml
src/site/apt/releasenotes.apt.vm
viewer-admin/src/main/webapp/META-INF/context.xml
viewer-admin/src/main/webapp/WEB-INF/web.xml
viewer/src/main/webapp/META-INF/context.xml
viewer/src/main/webapp/WEB-INF/web.xml

Flamingo 5.7.5 en Maven dependency updates

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet-config.js

fix ophalen van kaartlaag voor IbisFactsheet config component

---

pom.xml
src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/viewer-html/ibis/IbisEdit-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisEditHistorisch-config.js

zie ook: https://github.com/flamingo-geocms/flamingo/pull/1858

maak label breedte op editformulieren instelbaar

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/java/nl/b3p/viewer/stripes/IbisReportsActionBean.java
viewer/src/main/webapp/viewer-html/ibis/GridPanel.js
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet-config.js
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet.js

- gebruik try-with-resources om zeker te zijn dat stream wordt gesloten (https://www.deepcode.ai/app/gh/B3Partners/flamingo-ibis/08b11022ed9e1b32025d4875cf926cf39aa4c565/_/%2Fviewer%2Fsrc%2Fmain%2Fjava%2Fnl%2Fb3p%2Fviewer%2Fstripes%2FIbisReportsActionBean.java/java%2Fdc%2FMissingCloseOnSomePath/171/code)
- gebruik literals om javascript objecten te initialiseren ipv. `new ...`

DeepCode inspectie fixes

---

src/main/ddl/upgrade4.0-4.1-attribuut-alias.sql
src/main/ddl/upgrade4.0-4.1-views.sql
src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/WEB-INF/web.xml
viewer/src/main/webapp/WEB-INF/xsl/print/ibisfactsheet.xsl
viewer/src/main/webapp/viewer-html/ibis/IbisFactsheet.js

1. hernoem kolom bedrijventerrein#o_minverkoop ➜ b_minverkoop
2. hernoem kolom bedrijventerrein#o_maxverkoop ➜ b_maxverkoop
3. hernoem kolom bedrijventerrein#o_minhuur    ➜ b_minhuur
4. hernoem kolom bedrijventerrein#o_maxhuur    ➜ b_maxhuur

hernoem kolommen met prijzen zodat ze in aparte editor tab kunnen worden geladen

---

pom.xml
src/site/apt/releasenotes.apt.vm

en ook de maven plugins bijwerken

Upgrade Flamingo 5.7.6 ➜ 5.7.7

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/viewer-html/ibis/IbisEditHistorisch.js
viewer/src/main/webapp/viewer-html/ibis/WorkflowStatus.js

Verberg velden van "EditHistorisch" component die niet bewerkt mogen worden

---

src/site/apt/releasenotes.apt.vm
viewer/src/main/webapp/viewer-html/ibis/IbisEdit.js

afkeuren knop ook voor bedrijventerrein activeren

---

viewer/src/main/java/nl/b3p/viewer/stripes/IbisEditFeatureActionBean.java

close https://github.com/B3Partners/flamingo-ibis/issues/188

backend fix for issue 188, reject bedrijventerrein
